spring:
  application:
    name: key

  datasource:
    url: jdbc:postgresql://localhost:5432/key_service
    username: thang
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG


key:
  encryption:
    secret: ???

server:
  port: 8081